version: 1.1.3.0-alpha{build}
branches:
  only:
  - master
max_jobs: 15
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
install:
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019 Preview")

    {

    Write-Host "Installing .NET Core 3.0.100-preview-010184 SDK..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-sdk-3.0.100-preview-010184-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/a7e73d05-4e75-4543-ac41-fc69d2f617e5/3f65a44f90c9df66664b44e86b0e6d29/dotnet-sdk-3.0.100-preview-010184-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green


    Write-Host "Installing .NET Core 3.0.0-preview-27324-5 runtime..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-runtime-3.0.0-preview-27324-5-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/30594a10-9dcf-44c9-88c2-c559da2a0c6e/7cb211623fefc681750632dc6e5b3b36/dotnet-runtime-3.0.0-preview-27324-5-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green


    Write-Host "Installing .NET Framework 4.8 Targeting Pack..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\ndp48-devpack-enu.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/9854b5f2-2341-4136-ad7d-1d881ab8d603/e3a011f2a41a59b086f78d64e1c7a3fc/ndp48-devpack-enu.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green

    }
before_build:
- ps: >-
    nuget sources Add -Name "Generic Roslyn Analyzers" -Source https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json

    nuget restore
build:
  project: zlib.managed.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: w8jKLcMWVbTVBRRjl6k2eoRvajr5DpIB4XBhlEddCvx/9dSnDYbK5J0qXZXazE/E
  on:
    APPVEYOR_REPO_TAG: true
