version: 1.1.4.0-alpha{build}
branches:
  only:
  - master
max_jobs: 15
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
install:
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019 Preview")

    {

    Write-Host "Installing .NET Core 5.0.100-preview.4.20202.8 SDK..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-sdk-5.0.100-preview.4.20202.8-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100-preview.4.20202.8/dotnet-sdk-5.0.100-preview.4.20202.8-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green

    }
before_build:
- ps: nuget restore
build:
  project: zlib.managed.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: Mrzgs3GkYupK8M/4ZfFdjYR32bbkMWCsgzdL9fD/tfnSCOw4tzzmSUGj7mmm5ssV
  on:
    APPVEYOR_REPO_TAG: true
